package com.verifiedai.problem.application.classification;

public enum ProblemClassificationValidationFailure {
    SCHEMA_VERSION_MISMATCH,
    ONTOLOGY_VERSION_MISMATCH,

    STATUS_SEMANTICS_INVALID,

    PRIMARY_SKILL_REQUIRED,
    PRIMARY_SKILL_UNKNOWN,
    PRIMARY_SKILL_PARENT_INVALID,

    SECONDARY_SKILL_UNKNOWN,
    SECONDARY_SKILL_DUPLICATED,
    PRIMARY_SKILL_DUPLICATED_AS_SECONDARY,
    SECONDARY_SKILL_LIMIT_EXCEEDED,
    SECONDARY_SKILL_INCOMPATIBLE,

    DIFFICULTY_REQUIRED,

    REVIEW_REASON_REQUIRED,
    REVIEW_REASON_FORBIDDEN
}
