package com.verifiedai.problem.domain.model;

public enum ProblemParseUnsupportedReason {
    UNSUPPORTED_SUBJECT,
    UNSUPPORTED_TOPIC,
    UNSUPPORTED_TASK,
    UNSUPPORTED_STRUCTURE,
    MULTI_PART_UNSUPPORTED,
    DIAGRAM_REQUIRED,
    TEXT_HEAVY_WORD_PROBLEM,
    INSUFFICIENT_RECOGNITION_EVIDENCE,
    SCHEMA_CANNOT_REPRESENT
}
