from __future__ import annotations

MAX_OPERATIONS = 120
MAX_EXPRESSION_LENGTH = 256

CANONICAL_LIMITS_VERSION = "canonical-math-limits-v1"
MAX_CANONICAL_EXPRESSION_LENGTH = 512
MAX_CANONICAL_AST_NODES = 120
MAX_CANONICAL_AST_DEPTH = 32
MAX_CANONICAL_EXPONENT_MAGNITUDE = 12
MAX_CANONICAL_NUMERIC_DIGITS = 64
MAX_CANONICAL_FUNCTION_NESTING_DEPTH = 8
