package com.verifiedai.problem.domain.model.session;

public enum ProblemSessionNextAction {
    NONE,
    RESUME_UPLOAD,
    START_PREPROCESSING,
    RETRY_PREPROCESSING,
    START_RECOGNITION,
    WAIT_RECOGNITION,
    RETRY_RECOGNITION,
    START_PARSE,
    WAIT_PARSE,
    RETRY_PARSE,
    REVIEW_PARSE,
    CANONICALIZE,
    START_CLASSIFICATION,
    WAIT_CLASSIFICATION,
    RETRY_CLASSIFICATION,
    READY_FOR_SOLVE,
    RECAPTURE_OR_REIMPORT,
    UNSUPPORTED
}
